// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Support independent sessions by path namespace: /admin/*, /vendor/*, or default user
const pathname = typeof window !== 'undefined' ? window.location.pathname : '/';
const firstSegment = pathname.split('/').filter(Boolean)[0] || '';
const sessionNamespace = firstSegment === 'admin' ? 'admin' : firstSegment === 'vendor' ? 'vendor' : 'user';
const storageKey = `supabase-auth-${sessionNamespace}`;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});
